// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD-QEN7JTQ2mJm-jYOkOS4ziyUdsKwc2k',
    appId: '1:822822023460:web:73c4b45b3dfba6928583b1',
    messagingSenderId: '822822023460',
    projectId: 'notes-7958a',
    authDomain: 'notes-7958a.firebaseapp.com',
    storageBucket: 'notes-7958a.appspot.com',
    measurementId: 'G-087JKGV0YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB23KUk4Qswf5r7lyvD2s0Qa073KwleBB8',
    appId: '1:822822023460:android:c1cd4438367cf4e78583b1',
    messagingSenderId: '822822023460',
    projectId: 'notes-7958a',
    storageBucket: 'notes-7958a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxSiPN3SrpPCU95zuyBPIBQODJqCUW_xE',
    appId: '1:822822023460:ios:fe0ec9f686d279638583b1',
    messagingSenderId: '822822023460',
    projectId: 'notes-7958a',
    storageBucket: 'notes-7958a.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxSiPN3SrpPCU95zuyBPIBQODJqCUW_xE',
    appId: '1:822822023460:ios:63da9d0f3444b3888583b1',
    messagingSenderId: '822822023460',
    projectId: 'notes-7958a',
    storageBucket: 'notes-7958a.appspot.com',
    iosBundleId: 'com.example.notes.RunnerTests',
  );
}
