// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd9wsi1ZcaxNmsmdFQBJOnSSaCy4ukj0M',
    appId: '1:306433111726:web:6911f13606441dc0ee9f3f',
    messagingSenderId: '306433111726',
    projectId: 'company-3a055',
    authDomain: 'company-3a055.firebaseapp.com',
    databaseURL: 'https://company-3a055-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'company-3a055.appspot.com',
    measurementId: 'G-FSWCB8RYWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkTQtV-DzF_T1A_yYpYUbfVWx6QRLWT_I',
    appId: '1:306433111726:android:273e53f51a62990cee9f3f',
    messagingSenderId: '306433111726',
    projectId: 'company-3a055',
    databaseURL: 'https://company-3a055-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'company-3a055.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYTBDE0P4p6Pijl84QuIEAIPHJvX3pp0Y',
    appId: '1:306433111726:ios:c380f43df53ded2cee9f3f',
    messagingSenderId: '306433111726',
    projectId: 'company-3a055',
    databaseURL: 'https://company-3a055-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'company-3a055.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYTBDE0P4p6Pijl84QuIEAIPHJvX3pp0Y',
    appId: '1:306433111726:ios:c380f43df53ded2cee9f3f',
    messagingSenderId: '306433111726',
    projectId: 'company-3a055',
    databaseURL: 'https://company-3a055-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'company-3a055.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd9wsi1ZcaxNmsmdFQBJOnSSaCy4ukj0M',
    appId: '1:306433111726:web:67ff1a3e5b9a73d1ee9f3f',
    messagingSenderId: '306433111726',
    projectId: 'company-3a055',
    authDomain: 'company-3a055.firebaseapp.com',
    databaseURL: 'https://company-3a055-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'company-3a055.appspot.com',
    measurementId: 'G-GFR5KE6NTT',
  );

}